# Generated by Django 5.1.3 on 2024-12-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_stock_date_stock_dividend_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='annual_dividend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='yield_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
